using Mint.Util;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text;

namespace Mint.CodeGenerators
{
    public static class OpcodeHelper
    {
        [Flags]
        public enum FEnterFlags : byte
        {
            None = 0,
            Member = 1,
            Return = 2
        }

        public static readonly Dictionary<byte[], Dictionary<string, byte>> OpcodeByName = new(new ByteArrayComparer())
        {
            {
                new byte[] {0, 2, 0, 0},
                new Dictionary<string, byte>()
                {
                    { "ldsrzr", 0x01 },
                    { "ldsrbt", 0x02 },
                    { "ldsrc4", 0x03 },
                    { "ldsrca", 0x04 },
                    { "ldsrsr", 0x05 },
                    { "ldsrfz", 0x06 },
                    { "ldfrsr", 0x07 },
                    { "ldsrsv", 0x09 },
                    { "ldsra4", 0x0A },
                    { "stsrsr", 0x0C },
                    { "stsvsr", 0x0D },
                    { "addi32", 0x0E },
                    { "subi32", 0x0F },
                    { "muls32", 0x10 },
                    { "divs32", 0x11 },
                    { "mods32", 0x12 },
                    { "inci32", 0x13 },
                    { "deci32", 0x14 },
                    { "negs32", 0x15 },
                    { "addf32", 0x16 },
                    { "subf32", 0x17 },
                    { "mulf32", 0x18 },
                    { "divf32", 0x19 },
                    { "incf32", 0x1A },
                    { "decf32", 0x1B },
                    { "negf32", 0x1C },
                    { "lts32", 0x1D },
                    { "les32", 0x1E },
                    { "eqi32", 0x1F },
                    { "nei32", 0x20 },
                    { "ltf32", 0x21 },
                    { "lef32", 0x22 },
                    { "eqf32", 0x23 },
                    { "nef32", 0x24 },
                    { "eqbool", 0x27 },
                    { "nebool", 0x28 },
                    { "andi32", 0x29 },
                    { "ori32", 0x2A },
                    { "xori32", 0x2B },
                    { "ntbool", 0x2D },
                    { "slli32", 0x2E },
                    { "slri32", 0x2F },
                    { "jmp", 0x30 },
                    { "jmppos", 0x31 },
                    { "jmpneg", 0x32 },
                    { "fenter", 0x33 },
                    { "fleave", 0x34 },
                    { "fret", 0x35 },
                    { "call", 0x36 },
                    { "yield", 0x37 },
                    { "sppsh", 0x3A },
                    { "sppshz", 0x3B },
                    { "sppop", 0x3C },
                    { "addofs", 0x3D },
                    { "arpshz", 0x3E },
                    { "aridx", 0x3F },
                    { "arlen", 0x40 },
                    { "arpop", 0x41 }
                }
            },
            {
                new byte[] { 1, 0, 5, 0},
                new Dictionary<string, byte>()
                {
                    { "ldsrzr", 0x01 },
                    { "ldsrbt", 0x02 },
                    { "ldsrc4", 0x03 },
                    { "ldsrca", 0x04 },
                    { "ldsrsr", 0x05 },
                    { "ldsrfz", 0x06 },
                    { "ldfrsr", 0x07 },
                    { "ldfs2", 0x08 },
                    { "ldfs3f", 0x09 },
                    { "ldsrsv", 0x0C },
                    { "ldsra4", 0x0D },
                    { "stsrsr", 0x12 },
                    { "stofa4", 0x13 },
                    { "stsvsr", 0x14 },
                    { "addi32", 0x15 },
                    { "subi32", 0x16 },
                    { "muls32", 0x17 },
                    { "divs32", 0x18 },
                    { "mods32", 0x19 },
                    { "mulu32", 0x1A },
                    { "divu32", 0x1B },
                    { "modu32", 0x1C },
                    { "inci32", 0x1D },
                    { "deci32", 0x1E },
                    { "negs32", 0x1F },
                    { "addf32", 0x20 },
                    { "subf32", 0x21 },
                    { "mulf32", 0x22 },
                    { "divf32", 0x23 },
                    { "incf32", 0x24 },
                    { "decf32", 0x25 },
                    { "negf32", 0x26 },
                    { "lts32", 0x27 },
                    { "les32", 0x28 },
                    { "ltu32", 0x29 },
                    { "leu32", 0x2A },
                    { "eqi32", 0x2B },
                    { "nei32", 0x2C },
                    { "ltf32", 0x2D },
                    { "lef32", 0x2E },
                    { "eqf32", 0x2F },
                    { "nef32", 0x30 },
                    { "eqbool", 0x33 },
                    { "nebool", 0x34 },
                    { "eqptr", 0x35 },
                    { "neptr", 0x36 },
                    { "eqstr", 0x37 },
                    { "nestr", 0x38 },
                    { "andi32", 0x3C },
                    { "ori32", 0x3D },
                    { "xori32", 0x3E },
                    { "slli32", 0x41 },
                    { "slri32", 0x42 },
                    { "jmp", 0x43 },
                    { "jmppos", 0x44 },
                    { "jmpneg", 0x45 },
                    { "fenter", 0x46 },
                    { "fleave", 0x47 },
                    { "fret", 0x48 },
                    { "call", 0x49 },
                    { "callnv", 0x4A },
                    { "callnt", 0x4B },
                    { "yield", 0x4C },
                    { "sppshz", 0x50 },
                    { "sppop", 0x51 },
                    { "ldaddr", 0x53 },
                    { "arpshz", 0x54 },
                    { "aridx", 0x55 },
                    { "arpop", 0x56 },
                    { "cts32f", 0x5B },
                    { "cts32u", 0x5C },
                    { "ctu32s", 0x5D },
                    { "ctu32f", 0x5E },
                    { "ctf32s", 0x5F },
                    { "ctf32u", 0x60 }
                }
            }
        };
    }
}
